// angular/devkit/preview/mounter/mounter.ts
// required here to make sure that this is loaded before the compositions file
import '@angular/compiler';
import type { Type } from '@angular/core';
import { ngBootstrap, NgBootstrapOptions } from '@bitdev/angular.dev-services.preview.runtime';

export interface MounterOptions extends Omit<NgBootstrapOptions, "wrapper"| "hostElement"> {
  hostElement?: HTMLElement;
}

export function createMounter<C>(Wrapper?: Type<C>, options: MounterOptions = {}) {
  return async (Composition: Type<any>) => {
    const root = options.hostElement ?? document.getElementById('root');
    if (!root) {
      throw new Error('Host element not found, please provide an `hostElement` or add an element with id "root" to the DOM');
    }
    await ngBootstrap(Composition, {
      ...options,
      hostElement: root,
      wrapper: Wrapper,
    });
  };
}

export default createMounter;

// angular/integration/ng-elements-env/config/mounter.tsx
/* eslint-disable */
// @ts-nocheck
import React from 'react';
import { createRoot } from 'react-dom/client';
// required here to make sure that this is loaded before the compositions file
// import '@angular/compiler';
import { ngToReact } from '@bitdev/angular.dev-services.preview.runtime';

const container = document.getElementById('root') as HTMLElement;
const root = createRoot(container!);

/**
 * this mounts compositions into the DOM in the component preview.
 * this function can be overridden through ReactAspect.overrideCompositionsMounter() API
 * to apply custom logic for component DOM mounting.
 */
export default async (composition: any/* , previewContext: RenderingContext */) => {
  root.render(<div>{await ngToReact(composition)}</div>);
};
